namespace HotaRmgTemplateEditor.Domain.HotaData
{
	public static class Creatures
	{
		public static readonly Creature[] All;
		public static readonly IReadOnlyDictionary<int, Creature> Lookup;
		static Creatures()
		{
			All =
			[
				new Creature(0, "Pikemen", Town.Castle),
				new Creature(1, "Halberdiers", Town.Castle),
				new Creature(2, "Archers", Town.Castle),
				new Creature(3, "Marksmen", Town.Castle),
				new Creature(4, "Griffins", Town.Castle),
				new Creature(5, "Royal Griffins", Town.Castle),
				new Creature(6, "Swordsmen", Town.Castle),
				new Creature(7, "Crusaders", Town.Castle),
				new Creature(8, "Monks", Town.Castle),
				new Creature(9, "Zealots", Town.Castle),
				new Creature(10, "Cavaliers", Town.Castle),
				new Creature(11, "Champions", Town.Castle),
				new Creature(12, "Angels", Town.Castle),
				new Creature(13, "Archangels", Town.Castle),
				new Creature(14, "Centaurs", Town.Rampart),
				new Creature(15, "Centaur Captains", Town.Rampart),
				new Creature(16, "Dwarves", Town.Rampart),
				new Creature(17, "Battle Dwarves", Town.Rampart),
				new Creature(18, "Wood Elves", Town.Rampart),
				new Creature(19, "Grand Elves", Town.Rampart),
				new Creature(20, "Pegasi", Town.Rampart),
				new Creature(21, "Silver Pegasi", Town.Rampart),
				new Creature(22, "Dendroid Guards", Town.Rampart),
				new Creature(23, "Dendroid Soldiers", Town.Rampart),
				new Creature(24, "Unicorns", Town.Rampart),
				new Creature(25, "War Unicorns", Town.Rampart),
				new Creature(26, "Green Dragons", Town.Rampart),
				new Creature(27, "Gold Dragons", Town.Rampart),
				new Creature(28, "Gremlins", Town.Tower),
				new Creature(29, "Master Gremlins", Town.Tower),
				new Creature(30, "Stone Gargoyles", Town.Tower),
				new Creature(31, "Obsidian Gargoyles", Town.Tower),
				new Creature(32, "Stone Golems", Town.Tower),
				new Creature(33, "Iron Golems", Town.Tower),
				new Creature(34, "Magi", Town.Tower),
				new Creature(35, "Arch Magi", Town.Tower),
				new Creature(36, "Genies", Town.Tower),
				new Creature(37, "Master Genies", Town.Tower),
				new Creature(38, "Nagas", Town.Tower),
				new Creature(39, "Naga Queens", Town.Tower),
				new Creature(40, "Giants", Town.Tower),
				new Creature(41, "Titans", Town.Tower),
				new Creature(42, "Imps", Town.Inferno),
				new Creature(43, "Familiars", Town.Inferno),
				new Creature(44, "Gogs", Town.Inferno),
				new Creature(45, "Magogs", Town.Inferno),
				new Creature(46, "Hell Hounds", Town.Inferno),
				new Creature(47, "Cerberi", Town.Inferno),
				new Creature(48, "Demons", Town.Inferno),
				new Creature(49, "Horned Demons", Town.Inferno),
				new Creature(50, "Pit Fiends", Town.Inferno),
				new Creature(51, "Pit Lords", Town.Inferno),
				new Creature(52, "Efreet", Town.Inferno),
				new Creature(53, "Efreet Sultans", Town.Inferno),
				new Creature(54, "Devils", Town.Inferno),
				new Creature(55, "Arch Devils", Town.Inferno),
				new Creature(56, "Skeletons", Town.Necropolis),
				new Creature(57, "Skeleton Warrior", Town.Necropolis),
				new Creature(58, "Walking Dead", Town.Necropolis),
				new Creature(59, "Zombie", Town.Necropolis),
				new Creature(60, "Wight", Town.Necropolis),
				new Creature(61, "Wraith", Town.Necropolis),
				new Creature(62, "Vampire", Town.Necropolis),
				new Creature(63, "Vampire Lord", Town.Necropolis),
				new Creature(64, "Lich", Town.Necropolis),
				new Creature(65, "Power Lich", Town.Necropolis),
				new Creature(66, "Black Knight", Town.Necropolis),
				new Creature(67, "Dread Knight", Town.Necropolis),
				new Creature(68, "Bone Dragon", Town.Necropolis),
				new Creature(69, "Ghost Dragons", Town.Necropolis),
				new Creature(70, "Troglodytes", Town.Dungeon),
				new Creature(71, "Infernal Troglodyte", Town.Dungeon),
				new Creature(72, "Harpy", Town.Dungeon),
				new Creature(73, "Harpy Hag", Town.Dungeon),
				new Creature(74, "Beholder", Town.Dungeon),
				new Creature(75, "Evil Eye", Town.Dungeon),
				new Creature(76, "Medusa", Town.Dungeon),
				new Creature(77, "Medua Queen", Town.Dungeon),
				new Creature(78, "Minotaur", Town.Dungeon),
				new Creature(79, "Minotaur King", Town.Dungeon),
				new Creature(80, "Manticore", Town.Dungeon),
				new Creature(81, "Scorpicore", Town.Dungeon),
				new Creature(82, "Red Dragon", Town.Dungeon),
				new Creature(83, "Black Dragons", Town.Dungeon),
				new Creature(84, "Goblins", Town.Stronghold),
				new Creature(85, "Hobgoblin", Town.Stronghold),
				new Creature(86, "Wolf Rider", Town.Stronghold),
				new Creature(87, "Wolf Raider", Town.Stronghold),
				new Creature(88, "Orc", Town.Stronghold),
				new Creature(89, "Orc Chieftain", Town.Stronghold),
				new Creature(90, "Ogre", Town.Stronghold),
				new Creature(91, "Ogre Mage", Town.Stronghold),
				new Creature(92, "Roc", Town.Stronghold),
				new Creature(93, "Thunderbird", Town.Stronghold),
				new Creature(94, "Cyclops", Town.Stronghold),
				new Creature(95, "Cyclops King", Town.Stronghold),
				new Creature(96, "Behemoth", Town.Stronghold),
				new Creature(97, "Ancient Behemoths", Town.Stronghold),
				new Creature(98, "Gnolls", Town.Fortress),
				new Creature(99, "Gnoll Marauder", Town.Fortress),
				new Creature(100, "Lizardman", Town.Fortress),
				new Creature(101, "Lizard Warrior", Town.Fortress),
				new Creature(102, "Serpent Fly", Town.Fortress),
				new Creature(103, "Dragon Fly", Town.Fortress),
				new Creature(104, "Basilisk", Town.Fortress),
				new Creature(105, "Greater Basilisk", Town.Fortress),
				new Creature(106, "Gorgon", Town.Fortress),
				new Creature(107, "Mighty Gorgon", Town.Fortress),
				new Creature(108, "Wyvern", Town.Fortress),
				new Creature(109, "Wyvern Monarch", Town.Fortress),
				new Creature(110, "Hydra", Town.Fortress),
				new Creature(111, "Chaos Hydras", Town.Fortress),
				new Creature(118, "Pixies", Town.Conflux),
				new Creature(119, "Sprites", Town.Conflux),
				new Creature(112, "Air Elementals", Town.Conflux),
				new Creature(127, "Storm Elementals", Town.Conflux),
				new Creature(115, "Water Elementals", Town.Conflux),
				new Creature(123, "Ice Elementals", Town.Conflux),
				new Creature(114, "Fire Elementals", Town.Conflux),
				new Creature(129, "Energy Elementals", Town.Conflux),
				new Creature(113, "Earth Elementals", Town.Conflux),
				new Creature(125, "Magma Elementals", Town.Conflux),
				new Creature(120, "Psychic Elementals", Town.Conflux),
				new Creature(121, "Magic Elementals", Town.Conflux),
				new Creature(130, "Firebirds", Town.Conflux),
				new Creature(131, "Phoenixes", Town.Conflux),
				new Creature(153, "Nymphs", Town.Cove),
				new Creature(154, "Oceanids", Town.Cove),
				new Creature(155, "Crew Mates", Town.Cove),
				new Creature(156, "Seamen", Town.Cove),
				new Creature(157, "Pirates", Town.Cove),
				new Creature(158, "Corsairs", Town.Cove),
				new Creature(151, "Sea Dogs", Town.Cove),
				new Creature(159, "Stormbirds", Town.Cove),
				new Creature(160, "Ayssids", Town.Cove),
				new Creature(161, "Sea Witches", Town.Cove),
				new Creature(162, "Sorceresses", Town.Cove),
				new Creature(163, "Nix", Town.Cove),
				new Creature(164, "Nix Warriors", Town.Cove),
				new Creature(165, "Sea Serpents", Town.Cove),
				new Creature(166, "Haspids", Town.Cove),
				new Creature(139, "Peasants", Town.Neutral),
				new Creature(138, "Halflings", Town.Neutral),
				new Creature(143, "Rogues", Town.Neutral),
				new Creature(140, "Boars", Town.Neutral),
				new Creature(169, "Leprechauns", Town.Neutral),
				new Creature(141, "Mummies", Town.Neutral),
				new Creature(142, "Nomads", Town.Neutral),
				new Creature(167, "Satyrs", Town.Neutral),
				new Creature(137, "Sharpshooters", Town.Neutral),
				new Creature(116, "Gold Golems", Town.Neutral),
				new Creature(117, "Diamond Golems", Town.Neutral),
				new Creature(170, "Steel Golems", Town.Neutral),
				new Creature(144, "Trolls", Town.Neutral),
				new Creature(168, "Fangarms", Town.Neutral),
				new Creature(136, "Enchanters", Town.Neutral),
				new Creature(134, "Faerie Dragons", Town.Neutral),
				new Creature(133, "Crystal Dragons", Town.Neutral),
				new Creature(135, "Rust Dragons", Town.Neutral),
				new Creature(132, "Azure Dragons", Town.Neutral),
			];

			Lookup = All.ToDictionary(a => a.Id, a => a);
		}
	}
}
