namespace HotaRmgTemplateEditor.Domain.HotaData
{
	public static class Heroes
	{
		public static readonly Hero[] All;
		public static readonly IReadOnlyDictionary<int, Hero> Lookup;
		static Heroes()
		{
			All =
			[
				new Hero(0, Town.Castle, "Orrin", "Archery"),
				new Hero(1, Town.Castle, "Valeska", "Archers"),
				new Hero(2, Town.Castle, "Edric", "Griffins"),
				new Hero(3, Town.Castle, "Sylvia", "Navigation", DefaultAvailability.Conditional),
				new Hero(4, Town.Castle, "Lord Haart", "Estates"),
				new Hero(5, Town.Castle, "Sorsha", "Swordsmen"),
				new Hero(6, Town.Castle, "Christian", "Ballista"),
				new Hero(7, Town.Castle, "Tyris", "Cavaliers"),
				new Hero(8, Town.Castle, "Rion", "First Aid"),
				new Hero(9, Town.Castle, "Adela", "Bless"),
				new Hero(10, Town.Castle, "Cuthbert", "Weakness"),
				new Hero(11, Town.Castle, "Adelaide", "Frost Ring"),
				new Hero(12, Town.Castle, "Ingham", "Monks"),
				new Hero(13, Town.Castle, "Sanya", "Eagle Eye"),
				new Hero(14, Town.Castle, "Loynis", "Prayer"),
				new Hero(15, Town.Castle, "Caitlin", "Gold"),
				new Hero(16, Town.Rampart, "Mephala", "Armorer"),
				new Hero(17, Town.Rampart, "Ufretin", "Dwarves"),
				new Hero(18, Town.Rampart, "Jenova", "Gold"),
				new Hero(19, Town.Rampart, "Ryland", "Dendroids"),
				new Hero(20, Town.Rampart, "Thorgrim", "Resistance", DefaultAvailability.Disabled),
				new Hero(21, Town.Rampart, "Ivor", "Elves"),
				new Hero(22, Town.Rampart, "Clancy", "Unicorns"),
				new Hero(23, Town.Rampart, "Kyrre", "Logistics"),
				new Hero(24, Town.Rampart, "Coronius", "Slayer"),
				new Hero(25, Town.Rampart, "Uland", "Cure"),
				new Hero(26, Town.Rampart, "Elleshar", "Intelligence"),
				new Hero(27, Town.Rampart, "Gem", "First Aid"),
				new Hero(28, Town.Rampart, "Malcom", "Eagle Eye"),
				new Hero(29, Town.Rampart, "Melodia", "Fortune"),
				new Hero(30, Town.Rampart, "Alagar", "Ice Bolt"),
				new Hero(31, Town.Rampart, "Aeris", "Pegasi"),
				new Hero(32, Town.Tower, "Piquedram", "Gargoyles"),
				new Hero(33, Town.Tower, "Thane", "Genies"),
				new Hero(34, Town.Tower, "Josephine", "Golems"),
				new Hero(35, Town.Tower, "Neela", "Armorer"),
				new Hero(36, Town.Tower, "Torosar", "Ballista"),
				new Hero(37, Town.Tower, "Fafner", "Nagas"),
				new Hero(38, Town.Tower, "Rissa", "Mercury"),
				new Hero(39, Town.Tower, "Iona", "Genies"),
				new Hero(40, Town.Tower, "Astral", "Hypnotize"),
				new Hero(41, Town.Tower, "Halon", "Mysticism"),
				new Hero(42, Town.Tower, "Serena", "Eagle Eye"),
				new Hero(43, Town.Tower, "Daremyth", "Fortune"),
				new Hero(44, Town.Tower, "Theodorus", "Magi"),
				new Hero(45, Town.Tower, "Solmyr", "Chain Lightning"),
				new Hero(46, Town.Tower, "Cyra", "Haste"),
				new Hero(47, Town.Tower, "Aine", "Gold"),
				new Hero(48, Town.Inferno, "Fiona", "Hell Hounds"),
				new Hero(49, Town.Inferno, "Rashka", "Efreet"),
				new Hero(50, Town.Inferno, "Marius", "Demons"),
				new Hero(51, Town.Inferno, "Ignatius", "Imps"),
				new Hero(52, Town.Inferno, "Octavia", "Gold"),
				new Hero(53, Town.Inferno, "Calh", "Gogs"),
				new Hero(54, Town.Inferno, "Pyre", "Ballista"),
				new Hero(55, Town.Inferno, "Nymus", "Pit Fiends"),
				new Hero(56, Town.Inferno, "Ayden", "Intelligence"),
				new Hero(57, Town.Inferno, "Xyron", "Inferno (spell)"),
				new Hero(58, Town.Inferno, "Axsis", "Mysticism"),
				new Hero(59, Town.Inferno, "Olema", "Weakness"),
				new Hero(60, Town.Inferno, "Calid", "Sulfur"),
				new Hero(61, Town.Inferno, "Ash", "Bloodlust"),
				new Hero(62, Town.Inferno, "Zydar", "Sorcery"),
				new Hero(63, Town.Inferno, "Xarfax", "Fireball"),
				new Hero(64, Town.Necropolis, "Straker", "Walking Dead"),
				new Hero(65, Town.Necropolis, "Vokial", "Vampires"),
				new Hero(66, Town.Necropolis, "Moandor", "Liches"),
				new Hero(67, Town.Necropolis, "Charna", "Wights"),
				new Hero(68, Town.Necropolis, "Tamika", "Black Knights"),
				new Hero(69, Town.Necropolis, "Isra", "Necromancy"),
				new Hero(70, Town.Necropolis, "Clavius", "Gold"),
				new Hero(71, Town.Necropolis, "Galthran", "Skeletons", DefaultAvailability.Disabled),
				new Hero(72, Town.Necropolis, "Septienna", "Death Ripple"),
				new Hero(73, Town.Necropolis, "Aislinn", "Meteor Shower"),
				new Hero(74, Town.Necropolis, "Sandro", "Sorcery"),
				new Hero(75, Town.Necropolis, "Nimbus", "Eagle Eye"),
				new Hero(76, Town.Necropolis, "Thant", "Animate Dead"),
				new Hero(77, Town.Necropolis, "Xsi", "Stone Skin"),
				new Hero(78, Town.Necropolis, "Vidomina", "Necromancy"),
				new Hero(79, Town.Necropolis, "Nagash", "Gold"),
				new Hero(80, Town.Dungeon, "Lorelei", "Harpies"),
				new Hero(81, Town.Dungeon, "Arlach", "Ballista"),
				new Hero(82, Town.Dungeon, "Dace", "Minotaurs"),
				new Hero(83, Town.Dungeon, "Ajit", "Beholders"),
				new Hero(84, Town.Dungeon, "Damacon", "Gold"),
				new Hero(85, Town.Dungeon, "Gunnar", "Logistics"),
				new Hero(86, Town.Dungeon, "Synca", "Manticores"),
				new Hero(87, Town.Dungeon, "Shakti", "Troglodytes"),
				new Hero(88, Town.Dungeon, "Alamar", "Resurrection"),
				new Hero(89, Town.Dungeon, "Jaegar", "Mysticism"),
				new Hero(90, Town.Dungeon, "Malekith", "Sorcery"),
				new Hero(91, Town.Dungeon, "Jeddite", "Resurrection"),
				new Hero(92, Town.Dungeon, "Geon", "Eagle Eye"),
				new Hero(93, Town.Dungeon, "Deemer", "Meteor Shower"),
				new Hero(94, Town.Dungeon, "Sephinroth", "Crystal"),
				new Hero(95, Town.Dungeon, "Darkstorn", "Stone Skin"),
				new Hero(96, Town.Stronghold, "Yog", "Cyclops"),
				new Hero(97, Town.Stronghold, "Gurnisson", "Ballista"),
				new Hero(98, Town.Stronghold, "Jabarkas", "Orcs"),
				new Hero(99, Town.Stronghold, "Shiva", "Rocs"),
				new Hero(100, Town.Stronghold, "Gretchin", "Goblins"),
				new Hero(101, Town.Stronghold, "Krellion", "Ogres"),
				new Hero(102, Town.Stronghold, "Crag Hack", "Offense"),
				new Hero(103, Town.Stronghold, "Tyraxor", "Wolf Riders"),
				new Hero(104, Town.Stronghold, "Gird", "Sorcery"),
				new Hero(105, Town.Stronghold, "Vey", "Ogres"),
				new Hero(106, Town.Stronghold, "Dessa", "Logistics"),
				new Hero(107, Town.Stronghold, "Terek", "Haste"),
				new Hero(108, Town.Stronghold, "Zubin", "Precision"),
				new Hero(109, Town.Stronghold, "Gundula", "Offense"),
				new Hero(110, Town.Stronghold, "Oris", "Eagle Eye"),
				new Hero(111, Town.Stronghold, "Saurug", "Gems"),
				new Hero(112, Town.Fortress, "Bron", "Basilisks"),
				new Hero(113, Town.Fortress, "Drakon", "Gnolls"),
				new Hero(114, Town.Fortress, "Wystan", "Lizardmen"),
				new Hero(115, Town.Fortress, "Tazar", "Armorer"),
				new Hero(116, Town.Fortress, "Alkin", "Gorgons"),
				new Hero(117, Town.Fortress, "Korbac", "Serpent Flies"),
				new Hero(118, Town.Fortress, "Gerwulf", "Ballista"),
				new Hero(119, Town.Fortress, "Broghild", "Wyverns"),
				new Hero(120, Town.Fortress, "Mirlanda", "Weakness"),
				new Hero(121, Town.Fortress, "Rosic", "Mysticism"),
				new Hero(122, Town.Fortress, "Voy", "Navigation", DefaultAvailability.Conditional),
				new Hero(123, Town.Fortress, "Verdish", "First Aid"),
				new Hero(124, Town.Fortress, "Merist", "Stone Skin"),
				new Hero(125, Town.Fortress, "Styg", "Sorcery"),
				new Hero(126, Town.Fortress, "Andra", "Intelligence"),
				new Hero(127, Town.Fortress, "Tiva", "Eagle Eye"),
				new Hero(128, Town.Conflux, "Pasis", "Psychic Elementals"),
				new Hero(129, Town.Conflux, "Thunar", "Earth Elementals"),
				new Hero(130, Town.Conflux, "Ignissa", "Fire Elementals"),
				new Hero(131, Town.Conflux, "Lacus", "Water Elementals"),
				new Hero(132, Town.Conflux, "Monere", "Psychic Elementals"),
				new Hero(133, Town.Conflux, "Erdamon", "Earth Elementals"),
				new Hero(134, Town.Conflux, "Fiur", "Fire Elementals"),
				new Hero(135, Town.Conflux, "Kalt", "Water Elementals"),
				new Hero(136, Town.Conflux, "Luna", "Fire Wall"),
				new Hero(137, Town.Conflux, "Brissa", "Haste"),
				new Hero(138, Town.Conflux, "Ciele", "Magic Arrow"),
				new Hero(139, Town.Conflux, "Labetha", "Stone Skin"),
				new Hero(140, Town.Conflux, "Inteus", "Bloodlust"),
				new Hero(141, Town.Conflux, "Aenain", "Disrupting Ray"),
				new Hero(142, Town.Conflux, "Gelare", "Gold"),
				new Hero(143, Town.Conflux, "Grindan", "Gold"),
				new Hero(144, Town.Castle, "Sir Mullich", "Speed", DefaultAvailability.Disabled),
				new Hero(145, Town.Fortress, "Adrienne", "Fire Magic", DefaultAvailability.Disabled),
				new Hero(146, Town.Castle, "Catherine", "Swordsmen", DefaultAvailability.Disabled),
				new Hero(147, Town.Tower, "Dracon", "Enchanters", DefaultAvailability.Disabled),
				new Hero(148, Town.Rampart, "Gelu", "Sharpshooters", DefaultAvailability.Disabled),
				new Hero(149, Town.Stronghold, "Kilgor", "Behemoths", DefaultAvailability.Disabled),
				new Hero(150, Town.Necropolis, "Haart Lich", "Black Knights", DefaultAvailability.Disabled),
				new Hero(151, Town.Dungeon, "Mutare", "Dragons", DefaultAvailability.Disabled),
				new Hero(152, Town.Castle, "Roland", "Swordsmen", DefaultAvailability.Disabled),
				new Hero(153, Town.Dungeon, "Mutare Drake", "Dragons", DefaultAvailability.Disabled),
				new Hero(154, Town.Stronghold, "Boragus", "Ogres", DefaultAvailability.Disabled),
				new Hero(155, Town.Inferno, "Xeron", "Devils", DefaultAvailability.Disabled),
				new Hero(156, Town.Cove, "Corkes", "Offense"),
				new Hero(157, Town.Cove, "Jeremy", "Cannon"),
				new Hero(158, Town.Cove, "Illor", "Stormbirds"),
				new Hero(159, Town.Cove, "Derek", "Crew Mates", DefaultAvailability.Conditional),
				new Hero(160, Town.Cove, "Leena", "Gold"),
				new Hero(161, Town.Cove, "Anabel", "Pirates"),
				new Hero(162, Town.Cove, "Cassiopeia", "Nymphs"),
				new Hero(163, Town.Cove, "Miriam", "Scouting"),
				new Hero(164, Town.Cove, "Casmetra", "Sea Witches"),
				new Hero(165, Town.Cove, "Eovacius", "Clone"),
				new Hero(166, Town.Cove, "Spint", "Sorcery"),
				new Hero(167, Town.Cove, "Andal", "Crystal"),
				new Hero(168, Town.Cove, "Manfred", "Fireball"),
				new Hero(169, Town.Cove, "Zilare", "Forgetfulness"),
				new Hero(170, Town.Cove, "Astra", "Cure"),
				new Hero(171, Town.Cove, "Dargem", "Air Shield"),
				new Hero(172, Town.Cove, "Bidley", "Sea Dogs", DefaultAvailability.Disabled),
				new Hero(173, Town.Cove, "Tark", "Nix", DefaultAvailability.Disabled),
				new Hero(174, Town.Cove, "Elmore", "Navigation", DefaultAvailability.Conditional),
				new Hero(175, Town.Castle, "Beatrice", "Scouting", DefaultAvailability.Conditional),
				new Hero(176, Town.Fortress, "Kinkeria", "Learning", DefaultAvailability.Conditional),
				new Hero(177, Town.Necropolis, "Ranloo", "Ballista"),
				new Hero(178, Town.Rampart, "Giselle", "Interference", DefaultAvailability.Enabled)
			];

			Lookup = All.ToDictionary(a => a.Id, a => a);
		}
	}
}
