namespace HotaRmgTemplateEditor.UserControls
{
	public enum ZoneItemType
	{
		Player1Castle,
		Player1Town,
		Player2Castle,
		Player2Town,
		Player3Castle,
		Player3Town,
		Player4Castle,
		Player4Town,
		Player5Castle,
		Player5Town,
		Player6Castle,
		Player6Town,
		Player7Castle,
		Player7Town,
		Player8Castle,
		Player8Town,
		NeutralCastle,
		NeutralTown,
		ZoneValue,
		SawMill,
		OreMine,
		MercuryMine,
		SulfurMine,
		CrystalMine,
		GemsMine,
		GoldMine
	}
}
